#page title
page_title                                : Bike Around                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.croptracker.mobile.phonegap.inputsmanagement&hl=en_US                                        # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon-ba.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Bike Around                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Bike Around lets you create a ride in your area based on the time you have, the distance you want to cover, and the kinds of locations you want to visit.
enable_smart_app_banner                   : True                                     # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Foundry                               
your_link                                 : https://foundrymakes.com                  
your_city                                 : Minneapolis                                


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Create a Ride
    description                           : Create a Ride by selecting your interests as well as how much time and distance you want to cover.
    fontawesome_icon_name                 : route
    
  - title                                 : Start a Ride
    description                           : Once you approach a location, Bike around will automatically mark the location visited.
    fontawesome_icon_name                 : bicycle

  - title                                 : Ride with Friends
    description                           : Use the Share button to send your friends a 4-digit code so they can join your ride!
    fontawesome_icon_name                 : share-alt

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/appbanner_mustard.png                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#003049"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#FCFCFC"

link_color                                : "#003049"

app_title_color                           : "#003049"
app_price_color                           : "#003049"
app_description_color                     : "#003049"

feature_title_color                       : "#003049"
feature_text_color                        : "#868181"

feature_icons_foreground_color            : "#9AACB6"
feature_icons_background_color            : "#F5F5F5"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
